# Generated by Django 3.1 on 2020-08-19 13:08

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_google_dialog_flow_integration'),
    ]

    operations = [
        migrations.CreateModel(
            name='welcome_messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collect_email_id_from_anonymous_users', models.BooleanField(blank=True, default=False, null=True)),
                ('show_welcome_message_to_users', models.BooleanField(blank=True, default=False, null=True)),
                ('default_language', multiselectfield.db.fields.MultiSelectField(choices=[('English', 'English'), ('Mandarin Chinese', 'Mandarin Chinese'), ('Hindi', 'Hindi'), ('Spanish', 'Spanish'), ('Arabic', 'Arabic'), ('Bangla', 'Bangla'), ('Russian', 'Russian'), ('Portuguese', 'Portuguese'), ('Indonesian', 'Indonesian'), ('Urdu', 'Urdu')], max_length=87)),
                ('default_welcome_message', models.TextField(blank=True)),
            ],
        ),
    ]
