# Generated by Django 3.1 on 2020-08-20 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_company_configuration'),
    ]

    operations = [
        migrations.AddField(
            model_name='welcome_messages',
            name='cid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Admin.company_configuration'),
            preserve_default=False,
        ),
    ]
