# Generated by Django 3.1 on 2020-08-20 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_bot_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='google_dialog_flow_integration',
            name='bot_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Admin.bot_details'),
            preserve_default=False,
        ),
    ]
