# Generated by Django 3.1 on 2020-08-20 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_google_dialog_flow_integration_bot_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google_dialog_flow_integration',
            name='Service_account_private_key_file',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
