# Generated by Django 3.1 on 2020-08-21 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_auto_20200820_2144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Configurations',
            fields=[
                ('ccid', models.AutoField(primary_key=True, serialize=False)),
                ('cht_hty_rml_mnts', models.IntegerField(blank=True, null=True)),
                ('cht_hty_rml_hrs', models.IntegerField(blank=True, null=True)),
                ('cht_hty_rml_dys', models.IntegerField(blank=True, null=True)),
                ('cht_ssn_hty_indtr', models.BooleanField(default=False)),
                ('bt_rpls_dly_prd', models.IntegerField(blank=True, null=True)),
                ('no_of_thrd_alwd', models.IntegerField(blank=True, null=True)),
                ('cht_wdgt_dply_inditr', models.BooleanField(default=False)),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.bot_details')),
            ],
        ),
    ]
