# Generated by Django 3.1 on 2020-08-25 14:35

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_chat_configurations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_Widget_Customization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clr_cht_bt', colorful.fields.RGBColorField()),
                ('wdgt_pos_on_the_scrn', models.CharField(choices=[('Left', 'Left'), ('Right', 'Right')], default='Left', max_length=100)),
                ('upld_cstm_icon', models.ImageField(upload_to='images/')),
                ('ntn_snd_fr_bt', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third'), ('Fourth', 'Fourth'), ('Fifth', 'Fifth')], default='First', max_length=100)),
                ('bot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.bot_details')),
            ],
        ),
    ]
