# Generated by Django 3.1 on 2020-08-25 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_chat_widget_customization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_widget_customization',
            name='upld_cstm_icon',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
