# Generated by Django 3.1 on 2020-08-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_auto_20200825_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_configurations',
            name='cht_ssn_hty_indtr',
        ),
        migrations.AddField(
            model_name='chat_configurations',
            name='cht_hty_rml_opt',
            field=models.CharField(choices=[('First_Option', 'Remove chat widget history after a set period of time'), ('Second_Option', 'Remove chat session history on page refresh')], default='First_Option', max_length=100),
        ),
        migrations.AlterField(
            model_name='chat_configurations',
            name='bt_rpls_dly_prd',
            field=models.IntegerField(blank=True, help_text='0 second', null=True),
        ),
        migrations.AlterField(
            model_name='chat_configurations',
            name='cht_hty_rml_dys',
            field=models.IntegerField(blank=True, help_text='30 days', null=True),
        ),
        migrations.AlterField(
            model_name='chat_configurations',
            name='cht_hty_rml_hrs',
            field=models.IntegerField(blank=True, help_text='10 hours', null=True),
        ),
        migrations.AlterField(
            model_name='chat_configurations',
            name='cht_hty_rml_mnts',
            field=models.IntegerField(blank=True, help_text='30 minutes', null=True),
        ),
        migrations.AlterField(
            model_name='chat_configurations',
            name='cht_wdgt_dply_inditr',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
        migrations.AlterField(
            model_name='chat_configurations',
            name='no_of_thrd_alwd',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
