# Generated by Django 3.1 on 2020-08-31 10:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_image_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_widget_customization',
            name='id',
        ),
        migrations.AddField(
            model_name='chat_widget_customization',
            name='cwc_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chat_widget_customization',
            name='dflt_icn_fr_bts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.image_gallery'),
        ),
        migrations.AddField(
            model_name='chat_widget_customization',
            name='mfn_shwg_indct',
            field=models.BooleanField(choices=[(True, 'Yes'), (False, 'No')], default=True),
        ),
    ]
