# Generated by Django 3.1 on 2020-08-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_auto_20200831_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcome_messages',
            name='collect_email_id_from_anonymous_users',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
        migrations.AlterField(
            model_name='welcome_messages',
            name='show_welcome_message_to_users',
            field=models.BooleanField(blank=True, choices=[(True, 'Yes'), (False, 'No')], default=False, null=True),
        ),
    ]
