# Generated by Django 3.1 on 2020-09-02 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_auto_20200831_1822'),
    ]

    operations = [
        migrations.AlterField(
            model_name='google_dialog_flow_integration',
            name='Service_account_private_key_file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
