# Generated by Django 3.1 on 2020-09-02 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_auto_20200902_2006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='google_dialog_flow_integration',
            name='Service_account_private_key_file',
        ),
        migrations.AddField(
            model_name='google_dialog_flow_integration',
            name='service_account_private_key_file',
            field=models.FileField(blank=True, upload_to='documents/'),
        ),
    ]
