# Generated by Django 3.1 on 2020-09-21 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin', '0018_auto_20200902_2010'),
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_User_Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_status', models.CharField(choices=[('Super Admin', 'Super Admin'), ('Teammates', 'Teammates')], default='Teammates', max_length=100)),
                ('module', models.CharField(blank=True, max_length=20, null=True)),
                ('sub_module', models.CharField(blank=True, max_length=20, null=True)),
                ('bot_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.bot_details')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
